#!/usr/bin/env bash
# Install Android SDK command-line tools only (no Android Studio).
# Downloads platform-tools, build-tools, platform SDK, and NDK into .android-sdk/
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SDK_ROOT="${ANDROID_SDK_ROOT:-$ROOT/.android-sdk}"
CMDLINE_TOOLS_ZIP_URL="${CMDLINE_TOOLS_ZIP_URL:-https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip}"

# Match Expo SDK 54 / EAS defaults (override if your prebuild asks for newer versions).
PLATFORM_VERSION="${ANDROID_PLATFORM_VERSION:-36}"
BUILD_TOOLS_VERSION="${ANDROID_BUILD_TOOLS_VERSION:-36.0.0}"
NDK_VERSION="${ANDROID_NDK_VERSION:-27.1.12297006}"

usage() {
  cat <<EOF
Usage: ./scripts/setup-android-sdk.sh

Installs a headless Android SDK at:
  $SDK_ROOT

System packages still required (Debian/Ubuntu):
  sudo apt install openjdk-21-jdk-headless unzip curl ca-certificates

After setup, build with:
  pnpm build:android:local

Optional overrides:
  ANDROID_SDK_ROOT=/custom/path ./scripts/setup-android-sdk.sh
  ANDROID_PLATFORM_VERSION=35 ANDROID_NDK_VERSION=26.1.10909125 ...
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: missing command: $1" >&2
    exit 1
  fi
}

need_cmd curl
need_cmd unzip
need_cmd java

if ! java -version 2>&1 | grep -qE 'version "1[789]|version "[2-9][0-9]'; then
  echo "warning: Java 17+ recommended (sudo apt install openjdk-21-jdk-headless)." >&2
fi

mkdir -p "$SDK_ROOT/cmdline-tools"

if [[ ! -x "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]]; then
  echo "==> Downloading Android command-line tools"
  TMP_ZIP="$(mktemp /tmp/cmdline-tools.XXXXXX.zip)"
  trap 'rm -f "$TMP_ZIP"' EXIT
  curl -fsSL "$CMDLINE_TOOLS_ZIP_URL" -o "$TMP_ZIP"
  TMP_DIR="$(mktemp -d /tmp/cmdline-tools-unpack.XXXXXX)"
  unzip -q "$TMP_ZIP" -d "$TMP_DIR"
  rm -rf "$SDK_ROOT/cmdline-tools/latest"
  mv "$TMP_DIR/cmdline-tools" "$SDK_ROOT/cmdline-tools/latest"
  rm -rf "$TMP_DIR"
  echo "    installed sdkmanager at $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
fi

export ANDROID_HOME="$SDK_ROOT"
export ANDROID_SDK_ROOT="$SDK_ROOT"
export PATH="$SDK_ROOT/cmdline-tools/latest/bin:$SDK_ROOT/platform-tools:$PATH"

SDKMANAGER=(sdkmanager --sdk_root="$SDK_ROOT")
PACKAGES=(
  "platform-tools"
  "platforms;android-${PLATFORM_VERSION}"
  "build-tools;${BUILD_TOOLS_VERSION}"
  "ndk;${NDK_VERSION}"
  "cmake;3.22.1"
)

echo "==> Accepting Android SDK licenses"
# sdkmanager sometimes exits early and causes a SIGPIPE (exit code 141) on the `yes` side.
# That's fine as long as licenses were accepted; do not fail the whole script on that.
set +e
yes | "${SDKMANAGER[@]}" --licenses >/dev/null 2>&1
LICENSE_STATUS=$?
set -e
if [[ $LICENSE_STATUS -ne 0 && $LICENSE_STATUS -ne 141 ]]; then
  echo "warning: sdkmanager --licenses exited with code $LICENSE_STATUS" >&2
fi

echo "==> Installing SDK packages"
"${SDKMANAGER[@]}" "${PACKAGES[@]}"

ENV_FILE="$ROOT/.android-sdk.env"
cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-android-sdk.sh — source before building.
export ANDROID_HOME="$SDK_ROOT"
export ANDROID_SDK_ROOT="$SDK_ROOT"
export PATH="\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH"
EOF

echo ""
echo "Android SDK ready at: $SDK_ROOT"
echo "Environment file:   $ENV_FILE"
echo ""
echo "Next:"
echo "  source .android-sdk.env"
echo "  cp .env.example .env    # wrAuth URL + app key"
echo "  pnpm build:android:local"
